version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8-rc-alpine"
    networks:
      - users_nodetest-net
      - balances_nodetest-net
networks:
  users_nodetest-net:
    external: true
  balances_nodetest-net:
    external: true