version: '3'
services:
  balances_backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_HOST: 'mongo'
      RABBIT_HOST: 'rabbitmq'
    depends_on:
      - mongo
    networks:
      - nodetest-net
  mongo:
    image: "mongo:4-bionic"
    networks:
      - nodetest-net
networks:
  nodetest-net:
    driver: bridge