version: '3'
services:
  users_backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: 'mongo'
      RABBIT_HOST: 'rabbitmq'
    depends_on:
      - mongo
    networks:
      - nodetest-net
  mongo:
    image: "mongo:4-bionic"
    networks:
      - nodetest-net
networks:
  nodetest-net:
    driver: bridge